det_onnx_model_filepath : onnx_models/det.onnx
rec_onnx_model_filepath : onnx_models/rec.onnx
cls_onnx_model_filepath : onnx_models/cls.onnx
side_length_limit: 760
limit_type: min
image_path: assets/test_images
